"""changed the nature of relationships. Animals and owners are no longer linked through visits. Now, animals sits atop the structure and has a relationship with each model and other models have associations with each other through animals

Revision ID: 09476de77913
Revises: c58aacf285bf
Create Date: 2025-01-13 03:40:33.747471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09476de77913'
down_revision = 'c58aacf285bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_owners',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_animal_owners_animal_id_animals')),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_animal_owners_owner_id_owners')),
    sa.PrimaryKeyConstraint('animal_id', 'owner_id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint('fk_visits_owner_id_owners', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_visits_owner_id_owners', 'owners', ['owner_id'], ['id'])

    op.drop_table('animal_owners')
    # ### end Alembic commands ###
