"""added Vets table and modified relationships

Revision ID: 2653a0630bcd
Revises: cd305fca0401
Create Date: 2025-01-07 15:41:26.190473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2653a0630bcd'
down_revision = 'cd305fca0401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('animal_owners')
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_animals_vet_id_vets'), 'vets', ['vet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_animals_vet_id_vets'), type_='foreignkey')
        batch_op.drop_column('vet_id')

    op.create_table('animal_owners',
    sa.Column('animal_id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name='fk_animal_owners_animal_id_animals'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name='fk_animal_owners_owner_id_owners'),
    sa.PrimaryKeyConstraint('animal_id', 'owner_id')
    )
    op.drop_table('vets')
    # ### end Alembic commands ###
