"""adding new animal_owners table

Revision ID: 2bfe39f80ce3
Revises: cf85e960b305
Create Date: 2025-01-05 16:03:29.469153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bfe39f80ce3'
down_revision = 'cf85e960b305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_owners',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_animal_owners_animal_id_animals')),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_animal_owners_owner_id_owners')),
    sa.PrimaryKeyConstraint('animal_id', 'owner_id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_visits_animal_id_animals'), 'animals', ['animal_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_visits_owner_id_owners'), 'owners', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_visits_owner_id_owners'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_visits_animal_id_animals'), type_='foreignkey')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('animal_id')

    op.drop_table('animal_owners')
    # ### end Alembic commands ###
