"""added relationships to all models

Revision ID: 4fbad5e85b5e
Revises: 65f8e5834233
Create Date: 2025-01-05 12:13:39.328508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fbad5e85b5e'
down_revision = '65f8e5834233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_owners',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('owner.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_animal_owners_animal_id_animals')),
    sa.ForeignKeyConstraint(['owner.id'], ['owners.id'], name=op.f('fk_animal_owners_owner.id_owners')),
    sa.PrimaryKeyConstraint('animal_id', 'owner.id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('animal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_visits_owner_id_owners'), 'owners', ['owner_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_visits_animal_id_animals'), 'animals', ['animal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_visits_animal_id_animals'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_visits_owner_id_owners'), type_='foreignkey')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('animal_id')

    op.drop_table('animal_owners')
    # ### end Alembic commands ###
