"""created dogs table (id, name, DOB, species)

Revision ID: 569bae4cd248
Revises: 
Create Date: 2025-01-03 18:09:16.610198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569bae4cd248'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('DOB', sa.DateTime(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dogs')
    # ### end Alembic commands ###
