"""updated species to breed in dogs table

Revision ID: 75ee85ef528d
Revises: 569bae4cd248
Create Date: 2025-01-03 23:20:12.647545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ee85ef528d'
down_revision = '569bae4cd248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', sa.String(), nullable=True))
        batch_op.drop_column('species')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('breed')

    # ### end Alembic commands ###
