"""Added secondary_owner_id to visits

Revision ID: 7d6de0f1a607
Revises: 2653a0630bcd
Create Date: 2025-01-13 01:46:57.561541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6de0f1a607'
down_revision = '2653a0630bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_visits_secondary_owner_id_owners'), 'owners', ['secondary_owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_visits_secondary_owner_id_owners'), type_='foreignkey')
        batch_op.drop_column('secondary_owner_id')

    # ### end Alembic commands ###
