"""removed secondary owner id from visits table

Revision ID: c58aacf285bf
Revises: 7d6de0f1a607
Create Date: 2025-01-13 02:36:19.634689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58aacf285bf'
down_revision = '7d6de0f1a607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint('fk_visits_secondary_owner_id_owners', type_='foreignkey')
        batch_op.drop_column('secondary_owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_owner_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_visits_secondary_owner_id_owners', 'owners', ['secondary_owner_id'], ['id'])

    # ### end Alembic commands ###
