"""added summary column to visits table

Revision ID: cd305fca0401
Revises: 2bfe39f80ce3
Create Date: 2025-01-05 17:53:23.909200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd305fca0401'
down_revision = '2bfe39f80ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
