"""add animal_owners table

Revision ID: cf85e960b305
Revises: 4fbad5e85b5e
Create Date: 2025-01-05 15:21:35.248390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf85e960b305'
down_revision = '4fbad5e85b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_animal_owners_owner_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_animal_owners_owner_id_owners'), 'owners', ['owner_id'], ['id'])
        batch_op.drop_column('owner.id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner.id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_animal_owners_owner_id_owners'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'owners', ['owner.id'], ['id'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
