"""changed DOB to dob in Animal model

Revision ID: f2ae6c65735f
Revises: 09476de77913
Create Date: 2025-01-13 04:22:58.585255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ae6c65735f'
down_revision = '09476de77913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.drop_column('DOB')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DOB', sa.DATE(), nullable=True))
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
